pipeline {
    agent {
        label 'master'
    }
    parameters {
        choice(name: 'fluentbitHost', choices: ['spaghettini', 'syncronicity', 'refresh choices'], description: 'Target host for fluent bit agent')
        password(name: 'vaultToken', defaultValue: 'SECRET', description: 'User-generated Vault token')
    }
    environment {
        DUMMY_SPARSE_CHECKOUT_CONFIG = checkoutConfig("${params.fluentbitHost}")
        PATH = "/sw_ux/node/current/bin:/sw_ux/bin:$PATH"
        PIPELINE_ARTIFACTORY_CREDS = credentials('d7d54e7d-10c1-4466-a6d6-82ea62699416')
        FUNBUCKS_OUTPUT = "nr-funbucks/output"
        VAULT_ADDR = "https://vault-iit.apps.silver.devops.gov.bc.ca"
        VAULT_TOKEN = "${params.vaultToken}"
        FLUENTBIT_RELEASE = setFluentBitRelease("${params.fluentbitHost}")
        BIN_DIR = "/sw_ux/bin"
        AGENT_ROOT = "/apps_ux/agents"
        AGENT_HOME = "/apps_ux/agents/main"
        S6_SERVICE_DIR = "/apps_ux/s6_services/fluent-bit"
        HOST = setHost("${params.fluentbitHost}")
        HTTP_PROXY = setHttpProxy("${params.fluentbitHost}")
        HTTPS_PROXY = setHttpProxy("${params.fluentbitHost}")
        NO_PROXY = "https://vault-iit.apps.silver.devops.gov.bc.ca"
        ROLE_ID = "7cd218e3-b322-f394-4559-1caae025e075"
        VAULT_RELEASE = "1.7.1"
        ENVCONSUL_RELEASE = "0.11.0"
        JQ_RELEASE = "1.6"
        CD_USER = """${sh(
                returnStdout: true,
                script: "set +x; VAULT_ADDR=$VAULT_ADDR VAULT_TOKEN=$VAULT_TOKEN /sw_ux/bin/vault kv get -field=username_lowercase groups/appdelivery/jenkins_isss_cdua"
            )}"""
        CD_PASS = """${sh(
                returnStdout: true,
                script: "set +x; VAULT_ADDR=$VAULT_ADDR VAULT_TOKEN=$VAULT_TOKEN /sw_ux/bin/vault kv get -field=password groups/appdelivery/jenkins_isss_cdua"
            )}"""
        CI_USER = """${sh(
                returnStdout: true,
                script: "set +x; VAULT_ADDR=$VAULT_ADDR VAULT_TOKEN=$VAULT_TOKEN /sw_ux/bin/vault kv get -field=username_lowercase groups/appdelivery/jenkins_isss_ci"
            )}"""
        CI_PASS = """${sh(
                returnStdout: true,
                script: "set +x; VAULT_ADDR=$VAULT_ADDR VAULT_TOKEN=$VAULT_TOKEN /sw_ux/bin/vault kv get -field=password groups/appdelivery/jenkins_isss_ci"
            )}"""
        WRAPPING_TOKEN = """${sh(
                returnStdout: true,
                script: "set +x; VAULT_ADDR=$VAULT_ADDR VAULT_TOKEN=$VAULT_TOKEN /sw_ux/bin/vault write -wrap-ttl=120s -f -field=wrapping_token auth/vs_apps_approle/role/fluent_fluent-bit_prod/secret-id"
            )}"""
        SECRET_ID = """${sh(
                returnStdout: true,
                script: "set +x; VAULT_ADDR=$VAULT_ADDR VAULT_TOKEN=$WRAPPING_TOKEN /sw_ux/bin/vault unwrap -field=secret_id"
            )}"""
        APP_TOKEN = """${sh(
                returnStdout: true,
                script: "set +x; VAULT_ADDR=$VAULT_ADDR VAULT_TOKEN=$VAULT_TOKEN /sw_ux/bin/vault write -force -field=token auth/vs_apps_approle/login role_id=$ROLE_ID secret_id=$SECRET_ID"
            )}"""
    }
    stages {
        stage('Refresh params') {
            steps {
                script {
                    if( params.fluentbitHost == 'refresh choices' ) {
                        currentBuild.result = 'ABORTED'
                        error("Aborting the build.")
                    }
                }
            }
        }
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/feat/funbucks']],
                    doGenerateSubmoduleConfigurations: false,
                    gitTool: 'jgit',
                    submoduleCfg: [],
                    userRemoteConfigs: [
                        [
                            credentialsId: 'f1e16323-de75-4eac-a5a0-f1fc733e3621',
                            url: 'https://bwa.nrs.gov.bc.ca/int/stash/scm/fluentbit/fluentbit-deploy.git'
                        ]
                    ]
                ])
            }
        }
        stage('Setup funbucks') {
            steps {
                sh '''set +x; pass=`echo -n "$PIPELINE_ARTIFACTORY_CREDS_USR:$PIPELINE_ARTIFACTORY_CREDS_PSW" | openssl base64 -A`
echo "email=$PIPELINE_ARTIFACTORY_CREDS_USR
always-auth=true
strict-ssl=false
_auth=$pass
" > .npmrc'''
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    doGenerateSubmoduleConfigurations: false,
                    extensions: [[$class: 'RelativeTargetDirectory', relativeTargetDir: 'nr-funbucks']],
                    gitTool: 'jgit',
                    submoduleCfg: [],
                    userRemoteConfigs: [
                        [
                            credentialsId: 'f1e16323-de75-4eac-a5a0-f1fc733e3621',
                            url: 'https://bwa.nrs.gov.bc.ca/int/stash/scm/oneteam/oneteam-nr-funbucks.git'
                        ]
                    ]
                ])
                sh 'cd nr-funbucks; npm ci'
            }

        }
        stage('Build config') {
            steps {
                sh "nr-funbucks/bin/dev gen -m -s ${params.fluentbitHost}"
            }
        }
        stage('Stop fluent bit') {
            steps {
                sh 'scripts/stop_fluentbit.sh'
            }
        }
        stage('Deploy dependencies') {
            steps {
                sh 'scripts/deploy_dependencies.sh'
            }
        }
        stage('Deploy config') {
            steps {
                sh 'scripts/deploy_config.sh'
            }
        }
        stage('Deploy token') {
            steps {
                sh 'scripts/deploy_token.sh'
            }
        }
        stage('Start fluent bit') {
            steps {
                sh 'scripts/start_fluentbit.sh'
            }
        }
    }
}

// Helper Functions
def checkoutConfig(fluentbitHost) {
    checkout([
        $class: 'GitSCM',
        branches: [[name: '*/main']],
        doGenerateSubmoduleConfigurations: false,
        extensions: [
            [$class: 'RelativeTargetDirectory', relativeTargetDir: 'fb'],
            [$class: 'SparseCheckoutPaths',  sparseCheckoutPaths:[[$class:'SparseCheckoutPath', path: "config/server/${fluentbitHost}.json"]]]
        ],
        submoduleCfg: [],
        userRemoteConfigs: [
            [
                credentialsId: 'f1e16323-de75-4eac-a5a0-f1fc733e3621',
                url: 'https://bwa.nrs.gov.bc.ca/int/stash/scm/oneteam/oneteam-nr-funbucks.git'
            ]
        ]
    ])
    return 'done'
}
def setFluentBitRelease(fluentbitHost) {
    def props = readJSON file: "fb/config/server/${fluentbitHost}.json"
    return props.fluentBitRelease
}
def setHost(fluentbitHost) {
    def props = readJSON file: "fb/config/server/${fluentbitHost}.json"
    return props.address
}
def setHttpProxy(fluentbitHost) {
    def props = readJSON file: "fb/config/server/${fluentbitHost}.json"
    return props.proxy
}