import groovy.json.JsonSlurperClassic

@NonCPS
def jsonParse(def json) {
    new groovy.json.JsonSlurperClassic().parseText(json)
}

pipeline {
    agent {
        label 'master'
    }
    environment {
        PATH = "/sw_ux/node/current/bin:/sw_ux/bin:$PATH"
        PIPELINE_ARTIFACTORY_CREDS = credentials('d7d54e7d-10c1-4466-a6d6-82ea62699416')
        VAULT_ADDR = "https://vault-iit.apps.silver.devops.gov.bc.ca"
        BROKER_URL = "https://nr-broker.apps.silver.devops.gov.bc.ca"
        CONFIG_ROLE_ID = credentials('knox-vault-jenkins-aws-automation-role-id')
        BASIC_HTTP_USER = "brokeruser"
        BASIC_HTTP_PASSWORD = credentials('nr-broker-password')

        AWS_REGION = "ca-central-1"
        AWS_DEFAULT_REGION = "ca-central-1"
        OS_URL = "apm.io.nrs.gov.bc.ca"
        OS_DOMAIN = "nress-prod"
        HTTP_PROXY = "http://forwardproxy.nrs.bcgov:23128"
        HTTPS_PROXY = "http://forwardproxy.nrs.bcgov:23128"
        NO_PROXY = "https://vault-iit.apps.silver.devops.gov.bc.ca"
    }
    stages {
        stage('Checkout') {
            steps {
                checkout([
                    $class: 'GitSCM',
                    branches: [[name: '*/main']],
                    doGenerateSubmoduleConfigurations: false,
                    gitTool: 'jgit',
                    submoduleCfg: [],
                    userRemoteConfigs: [
                        [
                            credentialsId: 'f1e16323-de75-4eac-a5a0-f1fc733e3621',
                            url: 'https://bwa.nrs.gov.bc.ca/int/stash/scm/fluentbit/fluentbit-deploy.git'
                        ]
                    ]
                ])
            }
        }
        stage('Get credentials') {
            steps {
                script {
                    env.APP_TOKEN = sh(
                        returnStdout: true,
                        script: "set +x; scripts/vault_token.sh scripts/config-aws-automation.json"
                    )
                    env.AWS_ACCOUNT_NUMBER = sh(
                        returnStdout: true,
                        script: "set +x; VAULT_ADDR=$VAULT_ADDR VAULT_TOKEN=$APP_TOKEN /sw_ux/bin/vault kv get -field=aws_account_number apps/prod/jenkins/aws-automation"
                    )
                    env.AWS_ACCESS_KEY_ID = sh(
                        returnStdout: true,
                        script: "set +x; VAULT_ADDR=$VAULT_ADDR VAULT_TOKEN=$APP_TOKEN /sw_ux/bin/vault kv get -field=aws_access_key apps/prod/jenkins/aws-automation"
                    )
                    env.AWS_SECRET_ACCESS_KEY = sh(
                        returnStdout: true,
                        script: "set +x; VAULT_ADDR=$VAULT_ADDR VAULT_TOKEN=$APP_TOKEN /sw_ux/bin/vault kv get -field=aws_secret_access_key apps/prod/jenkins/aws-automation"
                    )
                    env.AWS_ASSUME_ROLE = sh(
                        returnStdout: true,
                        script: "set +x; VAULT_ADDR=$VAULT_ADDR VAULT_TOKEN=$APP_TOKEN /sw_ux/bin/vault kv get -field=aws_assume_role apps/prod/jenkins/aws-automation"
                    )
                }
            }
        }
        stage('Download Workflow CLI') {
            steps {
                sh 'scripts/automation_setup.sh'
            }
        }
        stage('Read Automation Queue') {
            steps {
                script {
                    // Read queue
                    def automationOutput = sh (
                        script: './workflow/bin/run automation-message',
                        returnStdout: true
                    )
                    .substring(17)
                    .trim()
                    def messageArr = jsonParse(automationOutput)
                    def agentMap = [:]
                    messageArr.each {
                        if (agentMap[it.agent]) {
                          return
                        }
                        def job = hudson.model.Hudson.instance.getItemByFullName("FLUENTBIT/fluentbit-start-agent")
                        def params = []
                        params += new StringParameterValue('fluentbitHost', it.server)
                        params += new StringParameterValue('fluentbitAgent', it.agent)
                        def paramsAction = new ParametersAction(params)
                        def cause = new hudson.model.Cause.RemoteCause("https://apm.io.nrs.gov.bc.ca", "Automation")
                        def causeAction = new hudson.model.CauseAction(cause)

                        // logger.info('Starting: ' + it.agent)
                        hudson.model.Hudson.instance.queue.schedule(job, 0, causeAction, paramsAction)
                        agentMap[it.agent] = true;
                    }
                }
            }
        }
    }
}
