@Library('polaris')
import ca.bc.gov.nrids.polaris.Podman
import ca.bc.gov.nrids.polaris.BrokerIntention
import ca.bc.gov.nrids.polaris.Vault
import ca.bc.gov.nrids.polaris.JenkinsUtil

def podman
def intention
def commonModule = [:]

pipeline {
    agent {
        label Podman.AGENT_LABEL_APP
    }
    environment {
        FB_INSTALL_USER="wwwadm"
        FB_RUN_USER="wwwsvr"
        FB_AGENT = "${params.fluentbitAgent}"
        FB_S6_SERVICE_HOME = "/apps_ux/s6_services"
        FB_BROKER_URL = "https://broker.io.nrs.gov.bc.ca"
        NR_BROKER_JWT = credentials('nr-fluentbit-broker-jwt')
        FB_ROLE_ID = credentials('knox-vault-fluentbit-app-role-id')
        IMAGE_TAG = "${params.imageTag}"
        AUTHFILE = "fluent-bit.auth.json"
    }
    stages {
        stage('Setup') {
            environment {
                HTTP_PROXY = "http://test-forwardproxy.nrs.bcgov:23128"
                FB_GIT_BRANCH = "${params.fbGitBranch}"
            }
            steps {
                script {
                    sh 'rm -rf fb && mkdir fb'
                    sh "git clone -b ${params.fbGitBranch} https://github.com/bcgov/nr-funbucks.git fb"
                    commonModule = load "pipelines/common.groovy"
                    intention = new BrokerIntention(NR_BROKER_JWT, readJSON(file: 'scripts/intention-fb-provision.json'))
                    intention.setEventDetails(
                        userName: JenkinsUtil.getCauseUserId(currentBuild, 'mbystedt@azureidir'),
                        url: env.BUILD_URL
                    )
                    intention.open()
                    intention.startAction("login")
                    def vaultToken = intention.provisionToken("login")
                    def vault = new Vault(vaultToken)
                    def registryCreds = vault.read('apps/data/prod/jenkins/jenkins-apps/artifactory')
                    env.REGISTRY_USERNAME = registryCreds['REGISTRY_USERNAME']
                    env.REGISTRY_PASSWORD = registryCreds['REGISTRY_PASSWORD']
                    env.FB_HOST = commonModule.getHost("${params.fluentbitHost}")
                    env.FB_SERVER_OS = commonModule.getServerOS("${params.fluentbitHost}")
                    if (env.FB_SERVER_OS != "linux" && env.FB_SERVER_OS != "windows") {
                        currentBuild.result = 'ABORTED'
                        error('Invalid server OS')
                    }
                    env.FB_BIN_DIR = "${env.FB_SERVER_OS == "linux" ? "/sw_ux/bin" : "E:/sw_nt"}"
                    env.FB_AGENT_ROOT = "${env.FB_SERVER_OS == "linux" ? "/apps_ux/agents" : "E:/apps_nt/agents"}"
                    env.FB_VAULT_CD_USER_FIELD = commonModule.getVaultCdUserField("${params.fluentbitHost}")
                    env.FB_VAULT_CD_PASS_FIELD = commonModule.getVaultCdPassField("${params.fluentbitHost}")
                    env.FB_VAULT_CD_PATH = commonModule.getVaultCdPath("${params.fluentbitHost}")
                    def vault_cd_path = "${env.FB_VAULT_CD_PATH}"
                    def cdCreds = vault.read(vault_cd_path.replaceFirst('/', '/data/'))
                    env.FB_CD_USER = cdCreds[env.FB_VAULT_CD_USER_FIELD]
                    env.FB_CD_PASS = cdCreds[env.FB_VAULT_CD_PASS_FIELD]
                    vault.revokeToken()
                    intention.startAction("provision")
                    def wrapped_fb_secret_id = intention.provisionSecretId("provision", FB_ROLE_ID)
                    env.WRAPPED_FB_SECRET_ID = wrapped_fb_secret_id
                }
            }
        }
        stage('Start fluent bit') {
            steps {
                script {
                    podman = new Podman(this, null, env.AUTHFILE, "artifacts.developer.gov.bc.ca/cc20-gen-docker-local")
                    podman.login(authfile: "${env.AUTHFILE}", options: "-u ${env.REGISTRY_USERNAME} -p ${env.REGISTRY_PASSWORD}")
                    podman.run("fb-helper:${params.imageTag}",
                        authfile: "${env.AUTHFILE}",
                        options: "-v \$(pwd)/files/ssh-config:/app/ssh-config -v \$(pwd)/scripts:/app/scripts -e 'FB_*' -e VAULT_ADDR=${Vault.KNOX_URL} -e 'WRAPPED_FB_SECRET_ID*'",
                        command: "scripts/${FB_SERVER_OS.toLowerCase()}/start_fluentbit_agent.sh")
                    podman.logout(authfile: "${env.AUTHFILE}")
                    intention.endAction("provision")
                    intention.endAction("login")
                }
            }
        }
    }
    post {
        success {
            script {
                intention.close(true)
            }
        }
        unstable {
            script {
                if (intention) {
                    intention.close(false)
                }
            }
        }
        failure {
            script {
                if (intention) {
                    intention.close(false)
                }
            }
        }
    }
}
